function PlotErosiveEventsTable(titlestr,ikind)
% This function plots selective columns of the ErosiveEventsTable
% generated by the CreateStormList.m script
% 
% Written By: Stephen Forczyk/Joydeb Saha
% Created: May 28,2024
% Revised: ----
% Classification: Unclassified/Public Domain

global RainFallFile1 RainFallFile2 RainFallFile1C RainFallFile2C;
global RainFallFile3 RainFallFile3C S;
global StationStr StationNum RainFallFile RainFallCatalogedFile;
global RainFallTime RainFallFlag RainFallAmt RainFallName;
global DetectTime NoDetectTime ErosiveList ErosiveList2 ErosiveIndices;
global ErosiveTimes SecondPassTimes ErosiveMonthlyCounts;

global ProvinceNames RainFallTime30 I30max;
global PotentialStorms ConsolidatedStorm  DefinedStorms BreakPoints;
global PS2 PS3 PS4 PS5 PS6 PS7 PS8 PS9 PS10 PS11 PS12 PS13 PS14 PS15 PS16;
global SPS2 SPS3 SPS4 SPS5 SPS6 SPS7 SPS8 SPS9 SPS10 SPS11 SPS12 SPS13 SPS14 SPS15 SPS16 
global SPDetectTime SPTimeIndices;
global numtimesstep SelectedYears SelStartIndex SelEndIndex numused numedused30;
global StormThreshTot StormThresh360 StormThresh15 StormBreakThresh;
global firstyearstr firstyear firstdaystr firstday firstmonthstr;
global firsthrstr firsthr firstminstr firstmin firstsecstr firstsec;
global lastyearstr lastyear lastdaystr lastday lastmonthstr;
global lasthrstr lasthr lastminstr lastmin lastsecstr lastsec;
global FoundData icataloged eventctr norainctr;
global I30 SumRain30 SUMKE30 ER30 VR30 KEnergy RainRate;
global RFactorTable RFactorTT DiagTable DiagTT;
global PotentialStormsTable PotentialStormsTT;
global PotentialStorms2Table PotentialStorms2TT;
global ErosiveEventTable ErosiveEventTT ErosiveEvent2Table ErosiveEvent2TT;
global ErosiveCountsTable EroisveCountsTT EventYears;
global StormBasicStats StormBasicStatsHdr;
global FirstPassItems SecondPassItems ErosiveItems;



global ColorList RGBVals ColorList2 xkcdVals LandColors;
global orange bubblegum brown brightblue almond beige wheat butterscotch

global datapath matlabpath moviepath tiffpath logfilepath mappath maskpath;
global tablepath jpegpath govjpegpath dailyfilepath rainfalldatapath csvfilepath;
global fid fid2;
global widd2 lend2;
global initialtimestr igrid ijpeg ilog ;
global vert1 hor1 widd lend;
global vert2 hor2 machine;
global chart_time;
global Fz1 Fz2;
global idirector mov izoom iwindow;
global vTemp TempMovieName iMovie iFastSave;
global RptGenPresent iCreatePDFReport pdffilename rpt chapter tocc lof lot;
global iLogo LogoFileName1 iCheckConfig;
global isumhourlyfiles sf1;% sf1 is the scale factor to go from kg/m^2 to inches of water

% if((iCreatePDFReport==1) && (RptGenPresent==1))
%     import mlreportgen.dom.*;
%     import mlreportgen.report.*;
% end
numrainevents=height(ErosiveEventTT);
eval(['cd ' jpegpath(1:length(jpegpath)-1)]);
movie_figure1=figure('position',[hor1 vert1 widd lend]);
set(gcf,'MenuBar','none');
if(ikind==1)
    plot(ErosiveEventTT.ErosiveTimes,ErosiveEventTT.Raintot,'--rs',...
    'LineWidth',1,...
    'MarkerSize',10,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1 0 0]);
    ylabel('Total Precip-mm','FontWeight','bold','FontSize',12);
    TotalPrecip=StormBasicStats{1,11};
elseif(ikind==2)
    plot(ErosiveEventTT.ErosiveTimes,ErosiveEventTT.Duration,'--gs',...
         'LineWidth',1,'MarkerSize',10,'MarkerEdgeColor','g',...
         'MarkerFaceColor',[1 0 0]);
    ylabel('Duration hr','FontWeight','bold','FontSize',12);
    TotalRainTimeSec1=StormBasicStats{2,11};
elseif(ikind==3)
    plot(ErosiveEventTT.ErosiveTimes,ErosiveEventTT.MaxOverRateLimit,'--bs',...
         'LineWidth',1,'MarkerSize',10,'MarkerEdgeColor','r',...
         'MarkerFaceColor',[0 1 0]);
    ylabel('#High Sample Rate','FontWeight','bold','FontSize',12);
    MaxRainRate=StormBasicStats{3,8};
elseif(ikind==4)
    plot(ErosiveEventTT.ErosiveTimes,ErosiveEventTT.MaxRate,'--rs',...
         'LineWidth',1,'MarkerSize',10,'MarkerEdgeColor','r',...
         'MarkerFaceColor',[0 1 1]);
    ylabel('MaxRainRate5min-mm/hr','FontWeight','bold','FontSize',12);
    MaxRainRate5Min=StormBasicStats{4,8};
elseif(ikind==5)
    plot(ErosiveEventTT.ErosiveTimes,ErosiveEventTT.MaxRain15,'--gs',...
         'LineWidth',1,'MarkerSize',10,'MarkerEdgeColor','r',...
         'MarkerFaceColor',[0 0 1]);
    ylabel('MaxRainRate15min-mm/hr','FontWeight','bold','FontSize',12);
    MaxRainRate15Min=StormBasicStats{5,8}; 
elseif(ikind==6)
    plot(ErosiveEventTT.ErosiveTimes,ErosiveEventTT.RainThresh2,'b',...
        ErosiveEventTT.ErosiveTimes,ErosiveEventTT.Pass15,'g',...
        ErosiveEventTT.ErosiveTimes,ErosiveEventTT.PassAll,'r');
    ylabel('RainThresholds','FontWeight','bold','FontSize',12);

 
end

set(gcf,'Position',[hor1 vert1 widd lend])
set(gca,'FontWeight','bold');
set(gca,'Position',[0.1300 0.1400 0.7450 0.7750]);
set(gca,'XGrid','on','YGrid','on');
set(gca,'XMinorGrid','on','YMinorGrid','on');
if(ikind==6)
    legend({'RainThresh2','Pass15','PassAll'},'Location','northeast');
    set(gca,'YLim',[0 3]);
end
ht=title(titlestr);
xlabel('Date','FontWeight','bold','FontSize',12);
%%Add a logo
if(iLogo==1)
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    ha =gca;
    uistack(ha,'bottom');
    haPos = get(ha,'position');
    %ha2=axes('position',[haPos(1:2), .1,.04,]);
    ha2=axes('position',[haPos(1)+.7,haPos(2)-.10, .21,.08,]);
    [x, ~]=imread(LogoFileName1);
    imshow(x);
    set(ha2,'handlevisibility','off','visible','off')
end
% Set up an axis for writing text at the bottom of the chart
newaxesh=axes('Position',[0 0 1 1]);
set(newaxesh,'XLim',[0 1],'YLim',[0 1]);
tx1=.10;
ty1=.04;
%TotalPrecipSec1InYear=TotalPrecipSec1/(25.4*YearPeriod);
if(ikind==1)
    txtstr1=strcat('Number Rain Events-',num2str(numrainevents),'-with a total of-',...
        num2str(TotalPrecip),'-mm of rain in the study period');
elseif(ikind==2)
    txtstr1=strcat('Total Rain Duration-',num2str(TotalRainTimeSec1),'-hrs');
elseif(ikind==3)
    txtstr1=strcat('NumEventsOver RainRate-',num2str(MaxRainRate),'-mm/hrs');
elseif(ikind==4)
    txtstr1=strcat('MaxRainRate5Min-',num2str(MaxRainRate5Min),'-mm/hr');
elseif(ikind==5)
    txtstr1=strcat('MaxRainRate15Min-',num2str(MaxRainRate15Min),'-mm/hr');
elseif(ikind==6)
    txtstr1=strcat('RainThresh2=12.7 mm','Pass15=6.35mm/hr');
end
txt1=text(tx1,ty1,txtstr1,'FontWeight','bold','FontSize',12);
tx2=.10;
ty2=.05;
%conversion found on this source
%https://www.metric-conversions.org/pressure/kilogram-force-per-square-meter-to-inches-of-water.htm
% maxdepth=val100*.039370;% this last number to depth of water in inches
% txtstr2=strcat(desc,'-','50 ptile=',num2str(val50,6),'-90 ptile=',num2str(val90,6),...
%     '-100 ptile=',num2str(val100,6),'-kg/m^2','-Max water depth=',num2str(maxdepth),'-in inches');
% txt2=text(tx2,ty2,txtstr2,'FontWeight','bold','FontSize',10);
set(newaxesh,'Visible','Off');

eval(['cd ' jpegpath(1:length(jpegpath)-1)]);
figstr=strcat(titlestr,'.jpg');
actionstr='print';
typestr='-djpeg';
[cmdString]=MyStrcat2(actionstr,typestr,figstr);
eval(cmdString);
pause(5)
close('all')
end
